language: python

python:
  - "2.7"

env:
  global:
    - secure: "Y/K0XnM8/CdANUT2ZCMb5Az1951wLQgwEc11cMWTK7bOHK6MfJ/WAXJmzI80NErJbj58h0pbMRp7YetfDi1PqjiCKU9j34eOh/dI5RUxorS4D4ccHA14x9IafeP/RgR/rTmJAe/tUxK5vU2/WwMFu/69bZ9g3qUFxDgTf8vhoW0="

install:
  - pip install -r requirements.txt -q
  - npm install less

before_script:
  - git config --global user.email "libsora25@gmail.com"
  - git config --global user.name "Travis"

script:
  - cd output
  - git checkout master
  - git pull
  - cd ..
  - cp CNAME output
  - make publish
  - cd output
  - git add -f .
  - git commit -a -m "add new site content"
  - test $? -eq "0" && git push https://${GH_TOKEN}@github.com/static-blog-sample/static-blog-sample.github.io.git master --quiet