language: python

python:
  - "2.7"

env:
  global:
    - secure: "KVyq2T0VewIq/0bDTtOQLXkFH2s5fvNlIorSFBMnk1Cdd8HrP3wazzfd0B1BDWItfqFJPW/DcEtnMlpUpNgnjB6oVvmum3dPNESctsXv2/bkUSCFhHJOF80dfdTV45d9YqwN1jGKeGJaMB1sol0Oj0Ufl9SWvX0EvZhG++SLafA="

install:
  - pip install -r requirements.txt

script:
  - make publish
  - git config --global user.email "libsora25@gmail.com"
  - git config --global user.name "Travis"
  - cd output
  - git pull origin master
  - git checkout master
  - git add -f .
  - git commit -a -m "add new site content"
  - git push https://${GH_TOKEN}@github.com/static-blog-sample/static-blog-sample.github.io.git master